Name:		grommunio-admin-web
Version:	4.0.0
Release:	2
Source0:	https://github.com/grommunio/admin-web/archive/refs/tags/%{version}.tar.gz
# Generated by running inside the source tree:
# export YARN_CACHE_FOLDER=$(pwd)/yarn-cache
# yarn install --frozen-lockfile
# tar cJf ../../../admin-web-%{version}-node-modules.tar.xz node_modules yarn-cache
Source1:	admin-web-%{version}-node-modules.tar.xz
Summary:	Admin web interface for the Grommunio groupware server
URL:		https://github.com/grommunio/admin-web
License:	AGPL-3.0
Group:		Servers
BuildArch:	noarch
BuildRequires:	make
BuildRequires:	yarn
BuildRequires:	python

%patchlist
admin-web-no-fs-extra-dep.patch

%description
Admin web interface for the Grommunio groupware server

%prep
%autosetup -p1 -n admin-web-%{version} -a 1
echo "%{version}" >.version

%build
export YARN_CACHE_FOLDER=$(pwd)/yarn-cache
%make_build YARN="yarn --offline --frozen-lockfile --ignore-engines"

# Replacement for postinstall.js:
rm -rf public/tinymce
cp -a node_modules/tinymce public/

make dist

%install
mkdir -p %{buildroot}%{_datadir}/grommunio-admin-web
cp -r dist/grommunio-admin-web-*/webapp/* %{buildroot}%{_datadir}/grommunio-admin-web/

mkdir -p %{buildroot}%{_sysconfdir}/nginx/sites-available
cat >%{buildroot}%{_sysconfdir}/nginx/sites-available/grommunio-admin.conf <<'EOF'
server {
	listen 80;
	server_name mailadmin.*;
	root %{_datadir}/grommunio-admin-web;
	index index.html;

	location / {
		try_files $uri $uri/ /index.html;
	}

	location /api/v1 {
		include uwsgi_params;
		uwsgi_pass unix:/run/grommunio/admin-api.socket;
		uwsgi_param HTTP_HOST $host;
		uwsgi_buffer_size 32k;
		uwsgi_buffers 8 32k;
	}

	location = /config.json {
		alias %{_sysconfdir}/grommunio-admin-common/config.json;
	}
}
EOF

mkdir -p %{buildroot}%{_sysconfdir}/grommunio-admin-common
cat >%{buildroot}%{_sysconfdir}/grommunio-admin-common/config.json <<'EOF'
{
        "mailWebAddress": "https://mail.YOUR.DOMAIN",
        "rspamdWebAddress": "https://antispam.YOUR.DOMAIN/",
        "defaultDarkMode": false,
        "defaultTheme": "grommunio",
        "loadAntispamData": true,
        "customImages": {}
}
EOF

%files
%{_datadir}/grommunio-admin-web
%config %{_sysconfdir}/nginx/sites-available/grommunio-admin.conf
%config(noreplace) %{_sysconfdir}/grommunio-admin-common/config.json
