Name:		grommunio-admin-web
Version:	4.0.0
Release:	1
Source0:	https://github.com/grommunio/admin-web/archive/refs/tags/%{version}.tar.gz
# Generated by running inside the source tree:
# yarn install --frozen-lockfile
# tar cJf ../../../admin-web-%{version}-node-modules.tar.xz node_modules
Source1:	admin-web-%{version}-node-modules.tar.xz
Summary:	Admin web interface for the Grommunio groupware server
URL:		https://github.com/grommunio/admin-web
License:	AGPL-3.0
Group:		Servers
BuildArch:	noarch
BuildRequires:	make
BuildRequires:	yarn
BuildRequires:	python

%description
Admin web interface for the Grommunio groupware server

%prep
%autosetup -p1 -n admin-web-%{version} -a 1
# postinstall pulls in another node module (fs-extra)
# that yarn doesn't see.
# Let's just drop it and reimplement what it does in bash
python -c "
import json
with open('package.json') as f:
    p = json.load(f)
p['version'] = '%{version}'
p.get('scripts', {}).pop('postinstall', None)
with open('package.json', 'w') as f:
    json.dump(p, f, indent=2)
"
echo "%{version}" >.version

%build
#export NODE_ENV=production
%make_build YARN="yarn --offline --frozen-lockfile --ignore-engines"

# Replacement for postinstall.js:
rm -rf public/tinymce
cp -a node_modules/tinymce public/

make dist

%install
mkdir -p %{buildroot}%{_datadir}/grommunio-admin-web
cp -r dist/grommunio-admin-web-*/webapp/* %{buildroot}%{_datadir}/grommunio-admin-web/

%files
%{_datadir}/grommunio-admin-web
